Phoning campaign scoreboard
EnMarche/Je-Marche pull request #128
Opened 2021-09-15 08:10 UTC by RomainGF

<img src="https://user-images.githubusercontent.com/24422094/133395563-fda6ca07-11f1-4d12-aaf3-4c7829f92ebc.png" width=240 />

2021-09-15 08:40 UTC, felginep requested changes

2021-09-15 08:40 UTC, felginep commented on src/core/entities/PhoningCampaign.ts
> +  caller: true
boolean plutôt que true non ? Le `caller` c'est pour mettre en gras la ligne qui correspond à toi

2021-09-15 08:40 UTC, felginep commented on src/data/restObjects/RestPhoningCampaign.ts
> +  caller: true
même remarque, `boolean` plutôt

2021-09-15 08:40 UTC, felginep commented on src/navigation/index.ts
> +export type PhoningCampaignScoreboardScreenNavigationProp = CompositeNavigationProp<
hum dans ton cas tu dois pouvoir t'en sortir juste avec 
```
export type PhoningCampaignScoreboardScreenProp = StackScreenProps<
  PhoningParamList,
  typeof Screen.phoningCampaignScoreboard
>
```

2021-09-15 08:40 UTC, felginep commented on src/screens/phoningCampaignBrief/PhoningCampaignBriefScreen.tsx
> +  const markdownStyle = { body: styles.contentContainer }
(pas prio) J'y pense, est-ce que le markdown utilise la même font que dans le reste de l'app ? Et est-ce que le markdown utilise les même typography que l'app. Si c'est pas le cas, on pourrait regarder pour styliser le md de manière à ce que ce soit cohérent avec le reste.

2021-09-15 08:40 UTC, felginep commented on src/screens/phoningCampaignScoreboard/PhoningCampaignScoreboardScreen.tsx
> +      <ScrollView>
Tu aurais mieux fait d'utiliser une flatlist, d'autant qu'il me semble que Victor voulait que le header   (Noms / Appelés / Complétés) reste sticky

2021-09-15 08:40 UTC, felginep commented on src/screens/shared/PhoningCampaignRankingView.tsx
> +import { DataTable } from 'react-native-paper'
hum on utilise jamais cette lib 🤔 cf mon commentaire sur la flatList (ou sectionList du framework)

2021-09-15 09:52 UTC, RomainGF commented on src/navigation/index.ts
> +export type PhoningCampaignScoreboardScreenNavigationProp = CompositeNavigationProp<
J'ai cette erreur quand j'essaie d'utiliser un StackScreenProp : 
```
Property 'setOptions' does not exist on type 'StackScreenProps<PhoningParamList, "PhoningCampaignScoreboard">
        navigation.setOptions({
```
C'est possible de mettre à jour le titre de la topbar autrement ?

2021-09-15 10:01 UTC, felginep commented on src/navigation/index.ts
> +export type PhoningCampaignScoreboardScreenNavigationProp = CompositeNavigationProp<
Ah trop bizarre 🤔

2021-09-15 15:38 UTC, RomainGF commented on src/screens/phoningCampaignScoreboard/PhoningCampaignScoreboardScreen.tsx
> +      <ScrollView>
J'ai changé pour une FlatList avec le header sticky du coup

2021-09-16 05:52 UTC, felginep commented on src/screens/phoning/campaign/PhoningCampaignRow.tsx
> +    borderRadius: Spacing.small,
pourquoi un borderRadius là ?

2021-09-16 05:52 UTC, felginep commented on src/screens/phoningCampaignScoreboard/PhoningCampaignScoreboardScreen.tsx
> +  const map = (scores: Array<PhoningCampaignScore>) => {
peut être mettre ca dans un mapper non?

2021-09-16 05:52 UTC, felginep commented on src/screens/shared/PhoningCampaignRankingView.tsx
> +      <View style={styles.row}>
Ah tu as fais comme ca pour le sticky header. Ca fonctionne mais tu pouvais aussi utiliser https://reactnative.dev/docs/sectionlist#stickysectionheadersenabled

2021-09-16 05:52 UTC, felginep commented on src/screens/shared/PhoningCampaignRankingView.tsx
> +      <View style={styles.row}>
Laissons comme ca hein, jsute pour info

2021-09-16 07:12 UTC, RomainGF commented on src/screens/phoning/campaign/PhoningCampaignRow.tsx
> +    borderRadius: Spacing.small,
C'est juste pour que ça rende mieux au clic avec un léger arrondi

2021-09-16 07:16 UTC, felginep commented on src/screens/phoning/campaign/PhoningCampaignRow.tsx
> +    borderRadius: Spacing.small,
En fait on s'attendrait plutôt sur ios à ce que le highlight se fasse sur toute la largeur de la card. A voir si c'est rapide à faire pour toi, sinon on laisse comme ca.

2021-09-16 08:19 UTC, felginep approved these changes

2021-09-16 08:19 UTC, merged