feat: actions menu
EnMarche/Je-Marche pull request #208
Opened 2021-11-16 13:57 UTC by ChawkiOS

2021-11-16 15:22 UTC, felginep requested changes

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionRow.tsx
> +      paddingRight: 8 * Spacing.unit,
pourquoi cet immense padding, met juste Spacing.margin ca ira

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionRow.tsx
> +      marginLeft: Spacing.unit,
d'après les maquettes c'est plutôt Spacing.margin

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionRow.tsx
> +      flexShrink: 1,
besoin de ca ?

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +    const fetch = (enablePhoning?: boolean) => {
pourquoi `enablePhoning` est optionnel ?

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +        keyExtractor={(item) => item.title}
utilise l'id plutôt comme key

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +
saut de ligne en trop

2021-11-16 15:22 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +    ...Typography.title,
manque la couleur du titre

2021-11-16 15:34 UTC, ChawkiOS commented on src/screens/actions/ActionsScreen.tsx
> +    const fetch = (enablePhoning?: boolean) => {
Ca fait une erreur ici
```
setStatefulState(
  new ViewState.Error(
    GenericErrorMapper.mapErrorMessage(error),
    fetch,
  ),
)
```
car dans `ViewState` c'est définit en tant que `() => void`

2021-11-16 15:37 UTC, ChawkiOS commented on src/screens/act/ActScreen.tsx
> +  navigation: any
C'est un ancien, c'était en wip

2021-11-16 15:43 UTC, ChawkiOS commented on src/screens/actions/ActionsScreen.tsx
> +    ...Typography.title,
il y est déjà dans `Typography.title`

2021-11-16 15:43 UTC, ChawkiOS commented on src/screens/actions/ActionRow.tsx
> +      ...Typography.title2,
idem, dans `Typography.title2`

2021-11-17 07:23 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +    const fetch = (enablePhoning?: boolean) => {
rien ne t'empêche de faire `() => fetch(enablePhoning)` au lieu de `fetch` non ?

2021-11-17 07:24 UTC, felginep commented on src/screens/actions/ActionRow.tsx
> +      paddingRight: 8 * Spacing.margin,
enlève le `8*` surtout :) je comprend pas à quoi sert ton `8`

2021-11-17 07:25 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +    ...Typography.title,
Ok my bad, 👍

2021-11-17 14:06 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +        .catch(fetch)
hum tu as pas une erreur sur le `.catch(fetch)` là ?

2021-11-17 14:51 UTC, ChawkiOS commented on src/screens/actions/ActionsScreen.tsx
> +        .catch(fetch)
en fait non !

2021-11-17 16:02 UTC, felginep approved these changes

2021-11-17 16:02 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +        .catch(fetch)
Typescript lève pas d'erreur, ce qui est étrange, tu es entrain de donner un méthode `(boolean) => void` au lieu de `(Error) => void`. Il faudrait remplacer par `.catch(() => fetch(false))` j'imagine?

2021-11-17 16:02 UTC, felginep commented on src/screens/actions/ActionsScreen.tsx
> +    useCallback(() => {
quel est l'intérêt du usecallback ici, vs avoir `fetch` en dépendance du `useEffect`?

2021-11-18 08:50 UTC, felginep approved these changes

2021-11-18 09:00 UTC, merged