feat: first and last tunnel screens
EnMarche/Je-Marche pull request #264
Opened 2021-12-21 12:49 UTC by ChawkiOS

2021-12-21 13:09 UTC, felginep requested changes
Je peux avoir une vidéo ios et android pour voir ce que ca donne stp ?

2021-12-21 13:09 UTC, felginep commented on src/navigation/index.ts
> +  TunnelDoorOpeningScreen: {
pourquoi pas nommé DoorToDoorTunnelOpeningScreen ? ca suivrait la convention que tu as prise au dessus

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/DoorToDoorBriefScreen.tsx
> +      // title: i18n.t('doorToDoor.tunnel.tutorial.title'),
il est fini ce todo ou pas ?

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/DoorToDoorBriefScreen.tsx
> +          new ViewState.Error(GenericErrorMapper.mapErrorMessage(error), () => {
utilise ViewStateUtils pour la gestion de l'erreur

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/DoorToDoorTunnelStartScreen.tsx
> +import Swiper from 'react-native-swiper'
au final tu as eu besoin de ca ?

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/DoorToDoorTunnelStartScreen.tsx
> +  // TODO - check the liste of campaign structure
on peut virer le todo ?

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/DoorToDoorTunnelStartScreen.tsx
> +        {/* TODO - Check array structure to map the list of Swiper */}
même question, toujours d'actualité. Une bonne manière d'écrire un TODO c'est de mettre la date et le nom de celui qui l'écrit, d'ailleurs

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/TunnelDoorOpeningScreen.tsx
> +          onPress={() => {}}
pourquoi cette fonction vide ?

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/TunnelDoorOpeningScreen.tsx
> +      <View style={styles.card}>
tu peux extraire ta card dans un composant si elle apparait 2 fois

2021-12-21 13:09 UTC, felginep commented on src/screens/doorToDoor/tunnel/TunnelDoorSuccessScreen.tsx
> +      {/* TODO - To change with API data */}
met ton nom + date

2021-12-21 13:34 UTC, ChawkiOS commented on src/screens/doorToDoor/tunnel/DoorToDoorBriefScreen.tsx
> +      // title: i18n.t('doorToDoor.tunnel.tutorial.title'),
Je vais voir avec Mathilde on aura un titre pour cette page ou pas

2021-12-21 13:35 UTC, ChawkiOS commented on src/screens/doorToDoor/tunnel/DoorToDoorTunnelStartScreen.tsx
> +import Swiper from 'react-native-swiper'
Oui c'est un peut compliqué avec le Carousell

2021-12-21 13:38 UTC, ChawkiOS commented on src/screens/doorToDoor/tunnel/TunnelDoorOpeningScreen.tsx
> +          onPress={() => {}}
Je suis suis sur un souci de navigation

2021-12-21 14:08 UTC, ChawkiOS commented
> Je peux avoir une vidéo ios et android pour voir ce que ca donne stp ?

Yes, dés que je fix le souci de navigation

2022-01-05 08:28 UTC, RomainGF commented
https://user-images.githubusercontent.com/24422094/148185163-a9838a37-104f-41e2-8270-5a6138af1220.mp4

https://user-images.githubusercontent.com/24422094/148185185-2f151a6e-2161-420f-9aaa-bbe914983c0b.mp4

2022-01-05 12:54 UTC, felginep approved these changes

2022-01-05 14:26 UTC, merged